import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useState } from 'react'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>АВТОПРОКАТ</h1>
        <h2>НАХОДКА</h2>
        <h3>АВТО ЗА 10 МИНУТ!</h3>
        <h3>АРЕНДА ОТ 3-Х СУТОК</h3>
        <Asker />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

const Asker = ({}) => {

  const [counter, setCounter] = useState(0);
  const [callMe, setCallMe] = useState(false);
  const [data, setData] = useState([""]);

  if(!callMe){

    switch(counter) {

      case 0:
        return(

          <section className = {styles.asker}>
            <Button text = "Я тороплюсь, позвоните мне" data = {data} counter = {counter} dataChanger = {setData} setterCount = {setCounter} setCallMe = {setCallMe} />
            <Button text = "Я выберу машину сам" data = {data} counter = {counter}  dataChanger = {setData} setterCount = {setCounter} />
            <span>{data[0]}</span>
          </section>

        )
        break;

      case 1:
        return(

          <>
            <h1>Тип кузова</h1>
            <section className = {styles.askerTypeCar}>
              <Button text = "Седан" data = {data} dataChanger = {setData} counter = {counter} setterCount = {setCounter} /> <Button text = "Хэтчбек" data = {data} dataChanger = {setData} counter = {counter} setterCount = {setCounter} /> <Button text = "Универсал" data = {data} dataChanger = {setData} counter = {counter}  setterCount = {setCounter} />
              <Button text = "Минивен" data = {data} dataChanger = {setData} counter = {counter}  setterCount = {setCounter} /> <Button text = "Кроссовер" data = {data} dataChanger = {setData} counter = {counter}  setterCount = {setCounter} /> <Button text = "Грузовик" data = {data}  dataChanger = {setData} counter = {counter}  setterCount = {setCounter} />
              <Button text = "4WD" data = {data} dataChanger = {setData} counter = {counter} setterCount = {setCounter} /> <Button text = "Гибрид" data = {data} dataChanger = {setData} counter = {counter} setterCount = {setCounter} />
              <span>{data}</span>
            </section>
          </>

        )
        break;

      case 2:
        return(
          <>
            <h1>Выберите год</h1>
            <section className = {styles.askerTypeCar}>
              <>
              <Button text = "2014" data = {data} dataChanger = {setData} counter = {counter} setterCount = {setCounter} /> <Button text = "2015" data = {data} dataChanger = {setData} counter = {counter} setterCount = {setCounter} /> <Button text = "2016" data = {data} dataChanger = {setData} counter = {counter} setterCount = {setCounter} />
              </>
              <>
              <Button text = "2015" data = {data}  dataChanger = {setData} counter = {counter} setterCount = {setCounter} /> <Button text = "2016" data = {data} dataChanger = {setData} counter = {counter} setterCount = {setCounter} /> <Button text = "2017" data = {data} dataChanger = {setData} counter = {counter} setterCount = {setCounter} />
              </>
              <span>{data}</span>
            </section>
          </>
        )
        break;

      case 3:
        return(
          <>
            <h1>Выберите цвет</h1>
            <section className = {styles.askerTypeCar}>
              <>
              <Button text = "Красный" data = {data} dataChanger = {setData} counter = {counter} setterCount = {setCounter} /> <Button text = "Белый" data = {data} dataChanger = {setData} counter = {counter} setterCount = {setCounter} /> <Button text = "Черный" data = {data} dataChanger = {setData} counter = {counter} setterCount = {setCounter} />
              </>
            </section>
          </>
        )
        break;

        case 4:
          return(
            <>
              <h1>Выберите цвет</h1>
              <section className = {styles.askerTypeCar}>
                <>
                <Button text = "Красный" data = {data}  dataChanger = {setData} counter = {counter} setterCount = {setCounter} /> <Button text = "Белый" data = {data}  dataChanger = {setData} counter = {counter} setterCount = {setCounter} /> <Button text = "Черный" data = {data} dataChanger = {setData} counter = {counter} setterCount = {setCounter} />
                </>
              </section>
            </>
          )
          break;

      default:
        return(
          <>
            <h1>Выберите год</h1>
            <section className = {styles.askerTypeCar}>
              <h1 className = {styles.centerHeading}>Ну типа, все. Все что я хотел Вам показать :) А это инфа, которую вы выбрали => {data}</h1>
              <span>{data}</span>
            </section>
          </>
        )
        break;
    }
  } else {
    return(

      <>
        <h1 className = {styles.centerHeading}>В течении нескольких минут Вам позвонит наш оператор! </h1>
      </>

    )
  }

}

const Button = ({ text , counter , data , dataChanger , setterCount , setCallMe}) => {

  const handleClick = ( evt ) => {

    if(typeof(setCallMe) == "undefined"){

      let count = counter;

        evt.preventDefault();

        setterCount(++count);
        dataChanger([...data,text]);

    } else {

        evt.preventDefault();

        setCallMe(true);

    }

  }

  return(
    <>
    <button onClick = { handleClick } className = {`${ styles.chooseButton } ${ styles.show }`}>
      {text}
    </button>
    </>
  )

}
