import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useState } from 'react'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>АВТОПРОКАТ</h1>
        <h2>НАХОДКА</h2>
        <h3>АВТО ЗА 10 МИНУТ!</h3>
        <h3>АРЕНДА ОТ 3-Х СУТОК</h3>
        <Asker />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

const Asker = ({}) => {

  const [counter,setCounter] = useState(0);
  const [callMe, setCallMe] = useState(false);

  if(!callMe){

    switch(counter) {

      case 0:
        return(

          <section className = {styles.asker}>
            <Button text = "Я тороплюсь, позвоните мне" counter = {counter}  setterCount = {setCounter} setCallMe = {setCallMe} />
            <Button text = "Я выберу машину сам" counter = {counter}  setterCount = {setCounter} />
          </section>

        )
        break;

      case 1:
        return(

          <>
            <h1>Тип кузова</h1>
            <section className = {styles.askerTypeCar}>
              <Button text = "Седан" counter = {counter} setterCount = {setCounter} /> <Button text = "Хэтчбек" counter = {counter} setterCount = {setCounter} /> <Button text = "Универсал" counter = {counter}  setterCount = {setCounter} />
              <Button text = "Минивен" counter = {counter}  setterCount = {setCounter} /> <Button text = "Кроссовер" counter = {counter}  setterCount = {setCounter} /> <Button text = "Грузовик" counter = {counter}  setterCount = {setCounter} />
              <Button text = "4WD" counter = {counter} setterCount = {setCounter} /> <Button text = "Гибрид" counter = {counter} setterCount = {setCounter} />
            </section>
          </>

        )
        break;

      case 2:
        return(
          <>
            <h1>Выберите год</h1>
            <section className = {styles.askerTypeCar}>
              <>
              <Button text = "2014" counter = {counter} setterCount = {setCounter} /> <Button text = "2015" counter = {counter} setterCount = {setCounter} /> <Button text = "2016" counter = {counter} setterCount = {setCounter} />
              </>
              <>
              <Button text = "2015" counter = {counter} setterCount = {setCounter} /> <Button text = "2016" counter = {counter} setterCount = {setCounter} /> <Button text = "2017" counter = {counter} setterCount = {setCounter} />
              </>
            </section>
          </>
        )
        break;

      case 3:
        return(
          <>
            <h1>Выберите цвет</h1>
            <section className = {styles.askerTypeCar}>
              <>
              <Button text = "Красный" counter = {counter} setterCount = {setCounter} /> <Button text = "Белый" counter = {counter} setterCount = {setCounter} /> <Button text = "Черный" counter = {counter} setterCount = {setCounter} />
              </>
            </section>
          </>
        )
        break;

        case 4:
          return(
            <>
              <h1>Выберите цвет</h1>
              <section className = {styles.askerTypeCar}>
                <>
                <Button text = "Красный" counter = {counter} setterCount = {setCounter} /> <Button text = "Белый" counter = {counter} setterCount = {setCounter} /> <Button text = "Черный" counter = {counter} setterCount = {setCounter} />
                </>
              </section>
            </>
          )
          break;

      default:
        return(
          <>
            <h1>Выберите год</h1>
            <section className = {styles.askerTypeCar}>
              <h1 className = {styles.centerHeading}>Ну типа, все. Все что я хотел Вам показать :)</h1>
            </section>
          </>
        )
        break;
    }
  } else {
    return(

      <>
        <h1 className = {styles.centerHeading}>В течении нескольких минут Вам позвонит наш оператор!</h1>
      </>

    )
  }

}

const Button = ({ text , counter , setterCount , setCallMe}) => {

  const handleClick = ( evt ) => {

    if(typeof(setCallMe) == "undefined"){

      let count = counter;

      evt.preventDefault();

      setterCount(++count);

    } else {

      evt.preventDefault();

      setCallMe(true);

    }

  }

  return(

    <button onClick = { handleClick } className = {`${ styles.chooseButton } ${ styles.show }`}>
      {text}
    </button>

  )

}
